#!/usr/bin/env python3
"""Prepare a non-submitting pure-FDM outer-zoom submission decision."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import tempfile

from fdm_smbh_delay.pure_fdm_outer_submission import (
    assess_pure_fdm_outer_submission,
)


def _write_json_atomic(path: Path, record: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as stream:
        stream.write(json.dumps(record, indent=2, sort_keys=True) + "\n")
        temporary = Path(stream.name)
    try:
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("specification", type=Path)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("preflight", type=Path)
    parser.add_argument("writer_source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument(
        "--runtime-attestation",
        type=Path,
        help=(
            "optional operator record from a compiled FDM writer integration "
            "test; it is never generated by this command"
        ),
    )
    args = parser.parse_args()
    decision = assess_pure_fdm_outer_submission(
        args.specification,
        args.manifest,
        args.preflight,
        args.writer_source,
        args.runtime_attestation,
    )
    record = decision.as_dict()
    destination = args.output.expanduser().resolve()
    _write_json_atomic(destination, record)
    print(json.dumps(record, indent=2, sort_keys=True))
    return 0 if decision.ready else 2


if __name__ == "__main__":
    raise SystemExit(main())
